## numpy array  operations 

In [1]:
import numpy as np

In [3]:
arr = np.array ([1,2,3,4,5,6,7,8,9])
print ("Basuic slicing ", arr[2:7])
print ("with step", arr[1:8:2])
print ("negative indexing ", arr [-3])

Basuic slicing  [3 4 5 6 7]
with step [2 4 6 8]
negative indexing  7


In [2]:
arr_2d = np.array ([[1,2,3],
                     [4,5,6],
                    [7,8,9]])
print ("specific element ", arr_2d[1,2])
print ("entire row ", arr_2d[0,:])


specific element  6
entire row  [1 2 3]


## Sorting 


In [9]:
unsorted = np.array ([3,1,4,1,5,9,2,6])
print ("sorted array ", np.sort(unsorted))

arr_2d_unsorted = np.array ([[3,1], [1,2], [2,3]])
print ("sorted array 2D by column", np.sort(arr_2d_unsorted ,axis = 0))

sorted array  [1 1 2 3 4 5 6 9]
sorted array 2D by column [[1 1]
 [2 2]
 [3 3]]


## Filter 

In [5]:
numbers = np.array ([1,2,3,4,5,6,7,8,9,10,11,12,13]) 
even_number = numbers[numbers%2 ==0]
print ("even numbers", even_number)

even numbers [ 2  4  6  8 10 12]


## Filter with mask

In [6]:
mask = numbers > 5 
print ("Numbers greter than 5 ", numbers[mask])

Numbers greter than 5  [ 6  7  8  9 10 11 12 13]


##  Fancy indexing vs np.where ()

In [8]:
indices = [0,2,3]
print(numbers[indices])

where_result = np.where(numbers>5)
print ("NP where ", numbers[where_result])


[1 3 4]
NP where  [ 6  7  8  9 10 11 12 13]


In [9]:
condition_array = np.where(numbers>5, "ture "," false")
print (condition_array)

[' false' ' false' ' false' ' false' ' false' 'ture ' 'ture ' 'ture '
 'ture ' 'ture ' 'ture ' 'ture ' 'ture ']


## Adding and removing data 

In [11]:
arr1 = np.array ([1,2,3])
arr2 = np.array ([4,5,6])

combined = np.concatenate((arr1,arr2))
print (combined)

[1 2 3 4 5 6]


## Array compatibility 

In [ ]:
a = np.array ([1,2,3])
b = np.array ([4,5,6])
c = np.array ([6,7,8])

print ("comatibility shapes", a.shape == b.shape)

comatibility shapes True


In [ ]:
original = np.array ([[1,2],[3,4]])
new_row = np.array ([[5,6]])

with_new_row = np.vstack((original ,new_row))
print (original )
print (with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack ((original , new_col))
print ("with new column", with_new_col)
                    


[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
with new column [[1 2 7]
 [3 4 8]]


In [21]:
arr = np.array ([1,2,3,4,5,6,7,8,9,10])
deleted = np.delete (arr, 2)
print ( "Array after deletion",deleted)

Array after deletion [ 1  2  4  5  6  7  8  9 10]
