### mini batch gradient decent by SKlearn

In [1]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_diabetes

X, y =load_diabetes(return_X_y=True)

In [2]:
from sklearn.model_selection import train_test_split 

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2 ,random_state=2)


In [46]:
import random
from sklearn.linear_model import SGDRegressor

sgd = SGDRegressor(learning_rate="constant",eta0=0.01)

batch_size = 35

for i in range (100):
    idx = random.sample(range(len(X_train)),batch_size)
    sgd.partial_fit(X_train[idx],y_train[idx])

In [47]:
y_pred =sgd.predict(X_test)

In [48]:
sgd.coef_

array([ 27.49096593,   5.13427107,  68.05973405,  54.817168  ,
        21.06907546,  16.39003928, -44.32222387,  44.80735728,
        65.91763183,  41.52825706])

In [49]:
sgd.intercept_

array([149.81600446])

In [128]:
from sklearn.metrics import r2_score

r2_score (y_test,y_pred)

0.45068513409005506

In [75]:
from sklearn.model_selection import train_test_split 

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2 ,random_state=2)

In [3]:
import random
class MBGDRegressor:
    def __init__(self,batch_size, learning_rate=0.01,epochs=100):
        self.coef_=None
        self.intercept=None
        self.lr=learning_rate
        self.epochs=epochs
        self.batch_size=batch_size
    
    def fit(self,X_train,y_train):
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])

        for i in range (self.epochs):

            for j in range(int(X_train.shape[0]/self.batch_size)):
                idx = random.sample(range(X_train.shape[0]),self.batch_size)
                  

                y_hat = np.dot(X_train[idx],self.coef_) + self.intercept_
                intercept_der = -2 * np.mean(y_train[idx] - y_hat)
                   
                self.intercept_=self.intercept_ -(self.lr*intercept_der)

             
                coef_der = -2 * np.dot((y_train[idx] - y_hat),X_train[idx])
                
                
                self.coef_=self.coef_-(self.lr*coef_der)

        print(self.intercept_,self.coef_)   

    def predict(self,X_test):
        return np.dot(X_test,self.coef_)+self.intercept_
        

In [4]:
mbr = MBGDRegressor(batch_size=int(X_train.shape[0]/50),learning_rate=0.01,epochs=100)


In [5]:
mbr.fit(X_train,y_train)

153.44155560051988 [  28.73504605 -141.43769135  451.29230476  300.96552926  -24.07448536
  -88.69638235 -191.56154712  113.12059647  400.05194103  117.49386128]


In [6]:
mbr.coef_

array([  28.73504605, -141.43769135,  451.29230476,  300.96552926,
        -24.07448536,  -88.69638235, -191.56154712,  113.12059647,
        400.05194103,  117.49386128])

In [7]:
mbr.intercept_

np.float64(153.44155560051988)

In [8]:
y_pred = mbr.predict(X_test)
y_pred


array([154.07467363, 197.26727576, 133.07837007, 107.32947302,
       260.25392278, 250.11704227, 112.48625171, 116.95825594,
        96.20538801, 188.49783162, 151.31672617, 174.17368477,
       182.82940284, 142.35833211, 281.39473897,  89.1330259 ,
       197.95919583, 147.59785056, 136.14908651, 134.22381186,
       145.4430956 , 178.86631002, 156.79757531, 176.41474815,
       128.61496936, 224.02541602, 201.00057446, 108.73116519,
        58.08095582, 240.23528685, 243.36501042, 116.10341395,
        70.9825588 , 101.2250637 , 204.26401182, 166.2743012 ,
       164.55433136, 194.51410521, 115.06188859, 238.90860301,
       141.61430543, 123.78768   , 187.83185163, 187.66605278,
       175.21207312, 145.18642203, 172.48314219, 294.10352971,
       110.72362971, 176.59246958, 250.88301506, 140.71285926,
       151.02370125, 134.05866776, 192.25999609, 102.32379951,
       138.87975164,  80.84906341, 160.29362548, 153.74621913,
       164.25079937, 165.69783548, 106.33019055, 221.72

In [9]:
from sklearn.metrics import r2_score

r2_score (y_test,y_pred)

0.4544485204730514