##numpy array and basic 

In [1]:
import numpy as np 

##creating array from list 

In [2]:
arr_1d = np.array( [1,2,3,4,5,6] )
print ("1D array:", arr_1d)

arr_2d = np.array( [[1,2,3], [4,5,6]] )
print ("2D array:", arr_2d)

1D array: [1 2 3 4 5 6]
2D array: [[1 2 3]
 [4 5 6]]


##list vs numpy array 

In [3]:
py_list =[1,2,3]
print ("python list multiplication",py_list *2)

np_array = np.array([1,2,3])
print ("python array multiplication",np_array *2)

import time 
start = time.time()
py_list = [i*2 for i in range(1000000)]
print ("\n list operation time :",time.time()-start)

start = time.time ()
np_array = np.arange(1000000)*2
print ("\n numpy operatin time :", time.time()-start)

python list multiplication [1, 2, 3, 1, 2, 3]
python array multiplication [2 4 6]

 list operation time : 0.16655468940734863

 numpy operatin time : 0.007976770401000977


##Creating array from scartch

In [4]:
zeros = np.zeros((3,4))
print("zeros array \n ", zeros )

one = np.ones((3,4))
print ("ones array:\n", one)

full = np.full((2,2),7)
print ("full array:\n",full)

random = np.random.random((2,3))
print ("random array:",random)

sequence = np.arange(0,10,2)
print("sequence array \n :" , sequence )




zeros array 
  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array:
 [[7 7]
 [7 7]]
random array: [[0.63345576 0.0363862  0.34844849]
 [0.15270323 0.8122429  0.67353534]]
sequence array 
 : [0 2 4 6 8]


##VECTOR , METRIX , TENSOR 

In [5]:
vector = np.array ([1,2,3])
print ("Vector :", vector )

metrix = np.array ([[1,2,3],[4,5,6]])
print (" \n Metrix: ", metrix )

tensor = np.array ([[[1,2],[3,4]],[[4,5],[6,7]]])
print ("\n Tensor :", tensor )

Vector : [1 2 3]
 
 Metrix:  [[1 2 3]
 [4 5 6]]

 Tensor : [[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]



##Array properties 

In [6]:
arr = np.array ([[1,2,3],[4,5,6]])
print ("shape ", arr.shape)
print ("Dimension", arr.ndim)
print ("Size", arr.size)
print ("Dtype ",arr.dtype)

shape  (2, 3)
Dimension 2
Size 6
Dtype  int64


Array reshaping 

In [7]:
arr = np.arange (12)
print ("original array", arr)

reshaped = arr.reshape ((3,4))
print (" \n Peshaped array",reshaped)

flattend = reshaped.flatten()
print ("\n flattend array ", flattend )

#raval (returns view , instead of copy )
raveled = reshaped.ravel()
print ("\n raveled array ", raveled)

#transpose 
transpose = reshaped.T
print ("\n Transposed array ", transpose)




original array [ 0  1  2  3  4  5  6  7  8  9 10 11]
 
 Peshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 flattend array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
